### PR TITLE
Feature/upstream id field fixes

### PR DESCRIPTION
**Pull request by hensoko**
There are several fields in swagger.json which have the wrong type assigned (string vs integer / number). This is mainly found with "id" and "*_id" fields. This PR should fix that.

See also #93

### CODE REVIEW

**Comment by hensoko** [comment]
Hey @Boulet- @awlx,

it seems that recreating the pull-request does not really help. Any idea how to proceed now?

**Comment by awlx** [comment]
Did you test the code you submitted? I can't really explain what is happeing if it works as submitted.

**Comment by hensoko** [comment]
@awlx Yeah I tested it and am using it daily and checked the commits several times

**Comment by awlx** [comment]
Ok, so I waiting for a confirm of #100 that this fixes this problem too. And will test it once more on my machine. If this all confirms we merge it.

Is that ok for you?

**Comment by hensoko** [comment]
Yeah sure :+1:

**Comment by hensoko** [comment]
Hey, any news on this? #98 seems not to be related so I wonder if the PR can be merged now?

**Pull request closed without merging**
