### PR TITLE
Netbox v2.11.11 Client Update

### PR DESCRIPTION
**Pull request by tagur87**
Update go-netbox to support Netbox v2.11.11

This adds support for many new features and has been automatically generated by go-swagger, using the makefile.

### CODE REVIEW

**Comment by tagur87** [comment]
@awlx @kobayashi 

Can you please review this so we can get this client updated to the latest version... I have already forked to continue using, but would love to see this make it into the main project again.

**Comment by awlx** [comment]
LGTM, thank you @tagur87 for your effort.

**Comment by tagur87** [comment]
> LGTM, thank you @tagur87 for your effort. I really would like to grant you permissions on this project, but I cannot because I don't have the permissions -.-.

Thanks so much! @awlx 
If you find a way to add me, let me know. I'd be glad to help.

**Comment by tagur87** [comment]
@awlx - Might need to do a `go mod tidy` to fix the dependencies...? Sorry I missed that myself.

**Comment by awlx** [comment]
No, worries. It seems to only break the build with golang 1.16.x which is interesting.

**Comment by awlx** [comment]
@tagur87 - Interesting ... still only golang 1.16 fails https://github.com/netbox-community/go-netbox/runs/3527552441

**Pull request merged**
