### PR TITLE
API changes for netbox 2.6

### PR DESCRIPTION
**Pull request by awlx**
As referenced in https://github.com/netbox-community/go-netbox/issues/41 this is the first PR to make go-netbox compatible with Netbox 2.6.

### CODE REVIEW

**Comment by quakelee** [comment]
Great effort! 
I forked a version for my needs as well, but just updated it partially.
I also did some change to make /api/dcim/_choice/ and /api/ipam/_choice/ work,
I'd like to merge them to this version.

Anyway, looking forward updating.

**Comment by awlx** [comment]
Can you make a PR against my personal repo for now @quakelee ? So we can merge the stuff in one go?

**Comment by awlx** [comment]
It's autogenerated from swagger API.

**Comment by quakelee** [comment]
> Can you make a PR against my personal repo for now @quakelee ? So we can merge the stuff in one go?

I'm so sorry, I met another issue in these days, so I didn't have time to follow up this PR.
I'll merge my changes base on your new code, let me make a new PR for it.

**Pull request merged**
